### ISSUE TITLE
ListingLoader.java line 62

### ISSUE THREAD

**Issue by vitamin-caig** [vitamin-caig/zxtune#14]
#### in app.zxtune.ui.browser.ListingLoader.loadInBackground

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/582c96f70aeb16625bee01ef](https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/582c96f70aeb16625bee01ef)

**Comment by vitamin-caig** [comment]
Non-fatal Exception: java.lang.NullPointerException
       at app.zxtune.ui.browser.ListingLoader.loadInBackground(ListingLoader.java:62)
       at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
       at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
