### ISSUE TITLE
'Out Of Memory while mmap' case

### ISSUE THREAD

**Issue by vitamin-caig** [vitamin-caig/zxtune#30]
#### in app.zxtune.fs.VfsCache.readMemoryMapped

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/582dfa7e0aeb16625bf9199d](https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/582dfa7e0aeb16625bf9199d)

**Comment by vitamin-caig** [comment]
Non-fatal Exception: java.io.IOException: mmap failed: ENOMEM (Out of memory)
       at java.nio.MemoryBlock.mmap(MemoryBlock.java:125)
       at java.nio.FileChannelImpl.map(FileChannelImpl.java:257)
       at app.zxtune.fs.VfsCache.readMemoryMapped(VfsCache.java:126)
       at app.zxtune.fs.VfsCache.readFrom(VfsCache.java:114)
       at app.zxtune.fs.VfsCache.readFrom(VfsCache.java:101)
       at app.zxtune.fs.VfsRootLocal$LocalFile.getContent(VfsRootLocal.java:216)
       at app.zxtune.Scanner.analyzeRealFile(Scanner.java:160)
       at app.zxtune.Scanner.analyzeFile(Scanner.java:122)
       at app.zxtune.Scanner.analyzeObject(Scanner.java:76)
       at app.zxtune.Scanner.analyzeRealObject(Scanner.java:69)
       at app.zxtune.Scanner.analyzeIdentifier(Scanner.java:58)
       at app.zxtune.Scanner.analyze(Scanner.java:51)
       at app.zxtune.playback.FileIterator$1.run(FileIterator.java:111)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.system.ErrnoException: mmap failed: ENOMEM (Out of memory)
       at libcore.io.Posix.mmap(Posix.java)
       at libcore.io.ForwardingOs.mmap(ForwardingOs.java:111)
       at java.nio.MemoryBlock.mmap(MemoryBlock.java:122)
       at java.nio.FileChannelImpl.map(FileChannelImpl.java:257)
       at app.zxtune.fs.VfsCache.readMemoryMapped(VfsCache.java:126)
       at app.zxtune.fs.VfsCache.readFrom(VfsCache.java:114)
       at app.zxtune.fs.VfsCache.readFrom(VfsCache.java:101)
       at app.zxtune.fs.VfsRootLocal$LocalFile.getContent(VfsRootLocal.java:216)
       at app.zxtune.Scanner.analyzeRealFile(Scanner.java:160)
       at app.zxtune.Scanner.analyzeFile(Scanner.java:122)
       at app.zxtune.Scanner.analyzeObject(Scanner.java:76)
       at app.zxtune.Scanner.analyzeRealObject(Scanner.java:69)
       at app.zxtune.Scanner.analyzeIdentifier(Scanner.java:58)
       at app.zxtune.Scanner.analyze(Scanner.java:51)
       at app.zxtune.playback.FileIterator$1.run(FileIterator.java:111)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
