### ISSUE TITLE
VisualizerView.java line 123

### ISSUE THREAD

**Issue by vitamin-caig** [vitamin-caig/zxtune#58]
#### in app.zxtune.ui.VisualizerView$SpectrumVisualizer.sizeChanged

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/5835ccc50aeb16625b33f91b](https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/5835ccc50aeb16625b33f91b)

**Comment by vitamin-caig** [comment]
Fatal Exception: java.lang.NegativeArraySizeException: -12
       at app.zxtune.ui.VisualizerView$SpectrumVisualizer.sizeChanged(VisualizerView.java:123)
       at app.zxtune.ui.VisualizerView.fillVisibleRect(VisualizerView.java:90)
       at app.zxtune.ui.VisualizerView.onSizeChanged(VisualizerView.java:67)
       at android.view.View.sizeChange(View.java:16153)
       at android.view.View.setFrame(View.java:16118)
       at android.view.View.layout(View.java:16009)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1948)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1724)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16019)
       at android.view.ViewGroup.layout(ViewGroup.java:5206)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2487)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2184)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6665)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:218)
       at android.app.ActivityThread.main(ActivityThread.java:5657)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

**Comment by vitamin-caig** [comment]
Fixed in 2cca87aaf11afc829851878161825ffbac9c031c
