### ISSUE TITLE
'Network on main thread' issue

### ISSUE THREAD

**Issue by vitamin-caig** [vitamin-caig/zxtune#73]
#### in app.zxtune.fs.HttpProvider.connect

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/583c37190aeb16625b5f60c2](https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/583c37190aeb16625b5f60c2)

**Comment by vitamin-caig** [comment]
Non-fatal Exception: android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
       at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
       at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:150)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:194)
       at java.net.URLConnection.getHeaderFieldInt(URLConnection.java:543)
       at java.net.URLConnection.getContentLength(URLConnection.java:315)
       at app.zxtune.fs.HttpProvider.connect(HttpProvider.java:48)
       at app.zxtune.fs.HttpProvider.getContent(HttpProvider.java:59)
       at app.zxtune.fs.joshw.RemoteCatalog.getFileContent(RemoteCatalog.java:54)
       at app.zxtune.fs.joshw.CachingCatalog.getFileContent(CachingCatalog.java:50)
       at app.zxtune.fs.VfsRootJoshw$AudiobaseDir.resolve(VfsRootJoshw.java:170)
       at app.zxtune.fs.VfsRootJoshw.resolvePath(VfsRootJoshw.java:115)
       at app.zxtune.fs.VfsRootJoshw.resolve(VfsRootJoshw.java:98)
       at app.zxtune.fs.VfsRootComposite.resolve(VfsRootComposite.java:45)
       at app.zxtune.fs.Vfs.resolve(Vfs.java:29)
       at app.zxtune.fs.VfsArchive.resolveFile(VfsArchive.java:115)
       at app.zxtune.fs.VfsArchive.resolve(VfsArchive.java:108)
       at app.zxtune.fs.VfsArchive.resolve(VfsArchive.java:101)
       at app.zxtune.ui.browser.BrowserController.getCurrentDir(BrowserController.java:157)
       at app.zxtune.ui.browser.BrowserController.loadCurrentDir(BrowserController.java:149)
       at app.zxtune.ui.browser.BrowserController.loadState(BrowserController.java:66)
       at app.zxtune.ui.BrowserFragment.onViewCreated(BrowserFragment.java:89)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:941)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:570)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
