### ISSUE TITLE
MotionEvent.java

### ISSUE THREAD

**Issue by vitamin-caig** [vitamin-caig/zxtune#80]
#### in android.view.MotionEvent.nativeGetAxisValue

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/583d8e430aeb16625b68f443](https://fabric.io/vitamins-projects/android/apps/app.zxtune/issues/583d8e430aeb16625b68f443)

**Comment by vitamin-caig** [comment]
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:1997)
       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1834)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1982)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2350)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2083)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2350)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2083)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2350)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2083)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2350)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2083)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2216)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1563)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2552)
       at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:260)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2164)
       at android.view.View.dispatchPointerEvent(View.java:8003)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4221)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4100)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3849)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3712)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3681)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3689)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5925)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5874)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5845)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6005)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5978)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6024)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:542)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)
